### PR TITLE
fix typos

### PR DESCRIPTION
**Pull request by innovimax**
**Please check if the PR fulfills these requirements:**

(Add x between brackets to check.)

- [x] I’ve read [contributing guidelines](../contributing.md)
- [ ] I’ve signed and sent the [Readium ICLA](http://readium.github.io/documents/Individual%20Contributor%20License%20Agreement.pdf)
- [ ] I’m making this pull request against the develop branch
- [ ] I’ve updated from the develop branch before proposing this pull request
- [ ] I’ve tested the changes for bug fixes and/or features
- [ ] I’ve documented new code

**What kind of change does this PR introduce?** (Bug fix, feature, docs update, other)

DOC UPDATE

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

**Other information:**

### CODE REVIEW

**Comment by JayPanoz** [comment]
@llemeurfr Quick question: for such PRs (e.g. typos, docs, etc.), do we really need the Readium ICLA signed and sent? Or is it just for code?

**Comment by llemeurfr** [comment]
I would consider the CSS authoring should get IP consideration as well as code. SO, yes, proposing modifications to a CSS should be covered by an ICLA IMO.

**Comment by JayPanoz** [comment]
Ok, since it’s a very minor change to the github template (i.e. administrative), unless someone disagrees, I think we can make an exception and merge the PR into the master branch – besides the corrected template would not be updated if it were merged into develop and would require another one from develop to master. 

I’m also going to commit the updated template to the contributing guidelines in the master branch directly (and reflect handling of the ICLA for typos). Then sync the develop branch.

**Comment by JayPanoz** [comment]
Thanks for catching those typos, @innovimax

**Pull request merged**
