### PR TITLE
Alpha release

### PR DESCRIPTION
**Pull request by JayPanoz**
Alpha version ships with:

- all the requirements in the Wiki’s Roadmap for this version;
- a new architecture (now customizable, usable through npm);
- build process;
- regressive CSS tests (visual);
- customizable flags;
- source maps;
- i18n (implem, docs, samples);
- a11y baseline (implem, docs);
- recommendations for fonts;
default styles for RTL and CJK scripts;
- various styles improvements;
- various bug fixes;
- EPUB compatibility doc;
- various corrections in docs;
- fonts for dyslexia.

### CODE REVIEW

**Comment by JayPanoz** [comment]
Quick question for you, @llemeurfr : how do we version this one? Like Readium Desktop (`alpha-1.0.0`) or do we stick to `0.8.0`? Maybe you want to keep consistency.

I wouldn’t necessarily be comfortable with the former since build and tests are still rough around the edges, comments are not removed in the built stylesheets yet, it would not clearly be representative of the current experimental status of vertical-writing, etc., so the latter makes most sense to me but I don’t have a strong opinion about that.

Also, I guess that versions can be pushed to master relatively quickly after being pushed to develop from now on, which is quite a milestone.

**Comment by JayPanoz** [comment]
**Don’t merge** until issue #31 is fixed.

**Comment by llemeurfr** [comment]
Re the version, the semantic versioning we have decided to use for iOS/Android/Desktop code would lead to 1.0.0-alpha.1. 
I don't see any issue adopting that numbering for Readium CSS, alpha meaning "rough around the edges".

**Comment by JayPanoz** [comment]
OK thanks let’s use this then. I’ll commit the version change on the develop branch.

**Comment by JayPanoz** [comment]
As far as I’m concerned, this is good to go as an alpha – even caught a late issue related to `table` in safeguards. 

I’ll let you review, especially the “admin” stuff (templates in `.github` folder, readme, `package.json`, etc.) before merging, @llemeurfr, if it’s ok for you. I’ll also get back to you tomorrow to deal with the communication around this release (updated article, etc.). 

From now on, we’ll be able to use a “beta release” milestone, and deal with more specific issues.

**Comment by llemeurfr** [comment]
The templates in .github are fine. The readme has been properly updated (esp. section Testing).  I can't judge the versioning contraints in package.json.

**Comment by JayPanoz** [comment]
Ok thanks!

I’ll get back to you by mail for the blogpost announcing the release, which has been updated + I need to check if links are working as expected since I anticipated their url in the draft. Not urgent though, it can wait one day or two.

**Pull request merged**
